/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_Arduino_LCD;

import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;
import static java.awt.image.ImageObserver.ERROR;
import java.io.OutputStream;
import java.util.Enumeration;
import javax.swing.JOptionPane;

/**
 *
 * @author alisonfernandez
 */
public class FRAME_LCD extends javax.swing.JFrame {

    private static final String b_temperatura = "0";
    private static final String b_hora = "1";
    private static final String b_mensaje1 = "2";
    private static final String b_mensaje2 = "3";
    private static final String b_mensaje3 = "4";
    
    private OutputStream output = null;
    SerialPort serialPort;
    private final String PUERTO = "/dev/cu.usbmodem1421";
    
    private static final int TIMEOUT = 2000;
    private static final int DATA_RATE = 9600;

    /**
     * Creates new form FRAME_LCD
     */
    public FRAME_LCD() {
        initComponents();
        inicializarConexion();
        setTitle("Programa Java - Arduino - LCD");
    }

    public void inicializarConexion(){
        CommPortIdentifier puertoID=null;
        Enumeration puertoEnum=CommPortIdentifier.getPortIdentifiers();
        
        while(puertoEnum.hasMoreElements()){
            CommPortIdentifier actualPuertoID=(CommPortIdentifier) puertoEnum.nextElement();
            if(PUERTO.equals(actualPuertoID.getName())){
                puertoID=actualPuertoID;
                break;
            }
        }
        
        if(puertoID==null){
            mostrarError("No se puede conectar al puerto");
            System.exit(ERROR);
        }
        
        try{
            serialPort = (SerialPort) puertoID.open(this.getClass().getName(), TIMEOUT);
            //Parámetros puerto serie
            
            serialPort.setSerialPortParams(DATA_RATE, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            
            output = serialPort.getOutputStream();
        } catch(Exception e){
            mostrarError(e.getMessage());
            System.exit(ERROR);
            
        }
    }
    
     private void enviarDatos(String datos){
        try{
            output.write(datos.getBytes());
        } catch(Exception e){
            mostrarError("ERROR");
            System.exit(ERROR);
        }
    }    
    
    public void mostrarError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boton_temperatura = new javax.swing.JButton();
        boton_hora = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        boton_mensaje1 = new javax.swing.JButton();
        boton_mensaje2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ingresa_mensaje3 = new javax.swing.JTextField();
        boton_mensaje3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PROGRAMA ARDUINO - JAVA -LCD");

        boton_temperatura.setText("Temperatura");
        boton_temperatura.setPreferredSize(new java.awt.Dimension(125, 30));
        boton_temperatura.setSize(new java.awt.Dimension(125, 30));
        boton_temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_temperaturaActionPerformed(evt);
            }
        });

        boton_hora.setText("Hora");
        boton_hora.setPreferredSize(new java.awt.Dimension(125, 30));
        boton_hora.setSize(new java.awt.Dimension(125, 30));
        boton_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_horaActionPerformed(evt);
            }
        });

        jLabel2.setText("MENSAJES");

        boton_mensaje1.setText("Mensaje 1");
        boton_mensaje1.setPreferredSize(new java.awt.Dimension(125, 30));
        boton_mensaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mensaje1ActionPerformed(evt);
            }
        });

        boton_mensaje2.setText("Mensaje 2");
        boton_mensaje2.setPreferredSize(new java.awt.Dimension(125, 30));
        boton_mensaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mensaje2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingresa un mensaje  desde un campo de texto:");

        ingresa_mensaje3.setText("Ingrese un mensaje aqui");
        ingresa_mensaje3.setPreferredSize(new java.awt.Dimension(200, 30));
        ingresa_mensaje3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresa_mensaje3ActionPerformed(evt);
            }
        });

        boton_mensaje3.setText("Enviar Mensaje 3");
        boton_mensaje3.setPreferredSize(new java.awt.Dimension(125, 30));
        boton_mensaje3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mensaje3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(boton_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(boton_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_mensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ingresa_mensaje3, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_mensaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(boton_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_mensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresa_mensaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_mensaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_horaActionPerformed
        // TODO add your handling code here:
        enviarDatos(b_hora);
    }//GEN-LAST:event_boton_horaActionPerformed

    private void boton_mensaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mensaje1ActionPerformed
        // TODO add your handling code here:
        enviarDatos(b_mensaje1);
    }//GEN-LAST:event_boton_mensaje1ActionPerformed

    private void boton_temperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_temperaturaActionPerformed
        // TODO add your handling code here:
        enviarDatos(b_temperatura);
    }//GEN-LAST:event_boton_temperaturaActionPerformed

    private void boton_mensaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mensaje2ActionPerformed
        // TODO add your handling code here:
        enviarDatos(b_mensaje2);
    }//GEN-LAST:event_boton_mensaje2ActionPerformed

    private void ingresa_mensaje3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresa_mensaje3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresa_mensaje3ActionPerformed

    private void boton_mensaje3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mensaje3ActionPerformed
        // TODO add your handling code here:
        enviarDatos(b_mensaje3);
    }//GEN-LAST:event_boton_mensaje3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRAME_LCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRAME_LCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRAME_LCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRAME_LCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRAME_LCD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_hora;
    private javax.swing.JButton boton_mensaje1;
    private javax.swing.JButton boton_mensaje2;
    private javax.swing.JButton boton_mensaje3;
    private javax.swing.JButton boton_temperatura;
    private javax.swing.JTextField ingresa_mensaje3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
